/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicPrivacyChoicesRouteImport } from './routes/_public/privacy-choices'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicCookiesRouteImport } from './routes/_public/cookies'
import { Route as AuthenticatedTrackingVerifyRouteImport } from './routes/_authenticated/tracking-verify'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated/tracking'
import { Route as AuthenticatedTestCenterRouteImport } from './routes/_authenticated/test-center'
import { Route as AuthenticatedResolvedVisitorsRouteImport } from './routes/_authenticated/resolved-visitors'
import { Route as AuthenticatedPrivacySettingsRouteImport } from './routes/_authenticated/privacy-settings'
import { Route as AuthenticatedIdentityRouteImport } from './routes/_authenticated/identity'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateListingRouteImport } from './routes/_authenticated/create-listing'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedSuper_adminRouteRouteImport } from './routes/_authenticated/_super_admin/route'
import { Route as AuthenticatedListingsIndexRouteImport } from './routes/_authenticated/listings.index'
import { Route as PublicUSlugRouteImport } from './routes/_public/u.$slug'
import { Route as PublicTourSlugRouteImport } from './routes/_public/tour.$slug'
import { Route as AuthenticatedListingsIdRouteImport } from './routes/_authenticated/listings.$id'
import { Route as AuthenticatedSuper_adminSponsorshipIndexRouteImport } from './routes/_authenticated/_super_admin/sponsorship.index'
import { Route as AuthenticatedListingsIdReportRouteImport } from './routes/_authenticated/listings.$id.report'
import { Route as AuthenticatedListingsIdAnalyticsRouteImport } from './routes/_authenticated/listings.$id.analytics'
import { Route as AuthenticatedSuper_adminSponsorshipNewRouteImport } from './routes/_authenticated/_super_admin/sponsorship.new'
import { Route as AuthenticatedSuper_adminSponsorshipCampaignIdRouteImport } from './routes/_authenticated/_super_admin/sponsorship.$campaignId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyChoicesRoute = PublicPrivacyChoicesRouteImport.update({
  id: '/privacy-choices',
  path: '/privacy-choices',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCookiesRoute = PublicCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedTrackingVerifyRoute =
  AuthenticatedTrackingVerifyRouteImport.update({
    id: '/tracking-verify',
    path: '/tracking-verify',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestCenterRoute = AuthenticatedTestCenterRouteImport.update({
  id: '/test-center',
  path: '/test-center',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResolvedVisitorsRoute =
  AuthenticatedResolvedVisitorsRouteImport.update({
    id: '/resolved-visitors',
    path: '/resolved-visitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrivacySettingsRoute =
  AuthenticatedPrivacySettingsRouteImport.update({
    id: '/privacy-settings',
    path: '/privacy-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdentityRoute = AuthenticatedIdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateListingRoute =
  AuthenticatedCreateListingRouteImport.update({
    id: '/create-listing',
    path: '/create-listing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuper_adminRouteRoute =
  AuthenticatedSuper_adminRouteRouteImport.update({
    id: '/_super_admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingsIndexRoute =
  AuthenticatedListingsIndexRouteImport.update({
    id: '/listings/',
    path: '/listings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicUSlugRoute = PublicUSlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTourSlugRoute = PublicTourSlugRouteImport.update({
  id: '/tour/$slug',
  path: '/tour/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedListingsIdRoute = AuthenticatedListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuper_adminSponsorshipIndexRoute =
  AuthenticatedSuper_adminSponsorshipIndexRouteImport.update({
    id: '/sponsorship/',
    path: '/sponsorship/',
    getParentRoute: () => AuthenticatedSuper_adminRouteRoute,
  } as any)
const AuthenticatedListingsIdReportRoute =
  AuthenticatedListingsIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedListingsIdRoute,
  } as any)
const AuthenticatedListingsIdAnalyticsRoute =
  AuthenticatedListingsIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedListingsIdRoute,
  } as any)
const AuthenticatedSuper_adminSponsorshipNewRoute =
  AuthenticatedSuper_adminSponsorshipNewRouteImport.update({
    id: '/sponsorship/new',
    path: '/sponsorship/new',
    getParentRoute: () => AuthenticatedSuper_adminRouteRoute,
  } as any)
const AuthenticatedSuper_adminSponsorshipCampaignIdRoute =
  AuthenticatedSuper_adminSponsorshipCampaignIdRouteImport.update({
    id: '/sponsorship/$campaignId',
    path: '/sponsorship/$campaignId',
    getParentRoute: () => AuthenticatedSuper_adminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/create-listing': typeof AuthenticatedCreateListingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/privacy-settings': typeof AuthenticatedPrivacySettingsRoute
  '/resolved-visitors': typeof AuthenticatedResolvedVisitorsRoute
  '/test-center': typeof AuthenticatedTestCenterRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/tracking-verify': typeof AuthenticatedTrackingVerifyRoute
  '/cookies': typeof PublicCookiesRoute
  '/privacy': typeof PublicPrivacyRoute
  '/privacy-choices': typeof PublicPrivacyChoicesRoute
  '/terms': typeof PublicTermsRoute
  '/listings/$id': typeof AuthenticatedListingsIdRouteWithChildren
  '/tour/$slug': typeof PublicTourSlugRoute
  '/u/$slug': typeof PublicUSlugRoute
  '/listings/': typeof AuthenticatedListingsIndexRoute
  '/sponsorship/$campaignId': typeof AuthenticatedSuper_adminSponsorshipCampaignIdRoute
  '/sponsorship/new': typeof AuthenticatedSuper_adminSponsorshipNewRoute
  '/listings/$id/analytics': typeof AuthenticatedListingsIdAnalyticsRoute
  '/listings/$id/report': typeof AuthenticatedListingsIdReportRoute
  '/sponsorship/': typeof AuthenticatedSuper_adminSponsorshipIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/company': typeof AuthenticatedCompanyRoute
  '/create-listing': typeof AuthenticatedCreateListingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/identity': typeof AuthenticatedIdentityRoute
  '/privacy-settings': typeof AuthenticatedPrivacySettingsRoute
  '/resolved-visitors': typeof AuthenticatedResolvedVisitorsRoute
  '/test-center': typeof AuthenticatedTestCenterRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/tracking-verify': typeof AuthenticatedTrackingVerifyRoute
  '/cookies': typeof PublicCookiesRoute
  '/privacy': typeof PublicPrivacyRoute
  '/privacy-choices': typeof PublicPrivacyChoicesRoute
  '/terms': typeof PublicTermsRoute
  '/listings/$id': typeof AuthenticatedListingsIdRouteWithChildren
  '/tour/$slug': typeof PublicTourSlugRoute
  '/u/$slug': typeof PublicUSlugRoute
  '/listings': typeof AuthenticatedListingsIndexRoute
  '/sponsorship/$campaignId': typeof AuthenticatedSuper_adminSponsorshipCampaignIdRoute
  '/sponsorship/new': typeof AuthenticatedSuper_adminSponsorshipNewRoute
  '/listings/$id/analytics': typeof AuthenticatedListingsIdAnalyticsRoute
  '/listings/$id/report': typeof AuthenticatedListingsIdReportRoute
  '/sponsorship': typeof AuthenticatedSuper_adminSponsorshipIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/_super_admin': typeof AuthenticatedSuper_adminRouteRouteWithChildren
  '/_authenticated/company': typeof AuthenticatedCompanyRoute
  '/_authenticated/create-listing': typeof AuthenticatedCreateListingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRoute
  '/_authenticated/identity': typeof AuthenticatedIdentityRoute
  '/_authenticated/privacy-settings': typeof AuthenticatedPrivacySettingsRoute
  '/_authenticated/resolved-visitors': typeof AuthenticatedResolvedVisitorsRoute
  '/_authenticated/test-center': typeof AuthenticatedTestCenterRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRoute
  '/_authenticated/tracking-verify': typeof AuthenticatedTrackingVerifyRoute
  '/_public/cookies': typeof PublicCookiesRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/privacy-choices': typeof PublicPrivacyChoicesRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_authenticated/listings/$id': typeof AuthenticatedListingsIdRouteWithChildren
  '/_public/tour/$slug': typeof PublicTourSlugRoute
  '/_public/u/$slug': typeof PublicUSlugRoute
  '/_authenticated/listings/': typeof AuthenticatedListingsIndexRoute
  '/_authenticated/_super_admin/sponsorship/$campaignId': typeof AuthenticatedSuper_adminSponsorshipCampaignIdRoute
  '/_authenticated/_super_admin/sponsorship/new': typeof AuthenticatedSuper_adminSponsorshipNewRoute
  '/_authenticated/listings/$id/analytics': typeof AuthenticatedListingsIdAnalyticsRoute
  '/_authenticated/listings/$id/report': typeof AuthenticatedListingsIdReportRoute
  '/_authenticated/_super_admin/sponsorship/': typeof AuthenticatedSuper_adminSponsorshipIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/company'
    | '/create-listing'
    | '/dashboard'
    | '/demo'
    | '/identity'
    | '/privacy-settings'
    | '/resolved-visitors'
    | '/test-center'
    | '/tracking'
    | '/tracking-verify'
    | '/cookies'
    | '/privacy'
    | '/privacy-choices'
    | '/terms'
    | '/listings/$id'
    | '/tour/$slug'
    | '/u/$slug'
    | '/listings/'
    | '/sponsorship/$campaignId'
    | '/sponsorship/new'
    | '/listings/$id/analytics'
    | '/listings/$id/report'
    | '/sponsorship/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/company'
    | '/create-listing'
    | '/dashboard'
    | '/demo'
    | '/identity'
    | '/privacy-settings'
    | '/resolved-visitors'
    | '/test-center'
    | '/tracking'
    | '/tracking-verify'
    | '/cookies'
    | '/privacy'
    | '/privacy-choices'
    | '/terms'
    | '/listings/$id'
    | '/tour/$slug'
    | '/u/$slug'
    | '/listings'
    | '/sponsorship/$campaignId'
    | '/sponsorship/new'
    | '/listings/$id/analytics'
    | '/listings/$id/report'
    | '/sponsorship'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/_super_admin'
    | '/_authenticated/company'
    | '/_authenticated/create-listing'
    | '/_authenticated/dashboard'
    | '/_authenticated/demo'
    | '/_authenticated/identity'
    | '/_authenticated/privacy-settings'
    | '/_authenticated/resolved-visitors'
    | '/_authenticated/test-center'
    | '/_authenticated/tracking'
    | '/_authenticated/tracking-verify'
    | '/_public/cookies'
    | '/_public/privacy'
    | '/_public/privacy-choices'
    | '/_public/terms'
    | '/_authenticated/listings/$id'
    | '/_public/tour/$slug'
    | '/_public/u/$slug'
    | '/_authenticated/listings/'
    | '/_authenticated/_super_admin/sponsorship/$campaignId'
    | '/_authenticated/_super_admin/sponsorship/new'
    | '/_authenticated/listings/$id/analytics'
    | '/_authenticated/listings/$id/report'
    | '/_authenticated/_super_admin/sponsorship/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy-choices': {
      id: '/_public/privacy-choices'
      path: '/privacy-choices'
      fullPath: '/privacy-choices'
      preLoaderRoute: typeof PublicPrivacyChoicesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/cookies': {
      id: '/_public/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof PublicCookiesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/tracking-verify': {
      id: '/_authenticated/tracking-verify'
      path: '/tracking-verify'
      fullPath: '/tracking-verify'
      preLoaderRoute: typeof AuthenticatedTrackingVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test-center': {
      id: '/_authenticated/test-center'
      path: '/test-center'
      fullPath: '/test-center'
      preLoaderRoute: typeof AuthenticatedTestCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resolved-visitors': {
      id: '/_authenticated/resolved-visitors'
      path: '/resolved-visitors'
      fullPath: '/resolved-visitors'
      preLoaderRoute: typeof AuthenticatedResolvedVisitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy-settings': {
      id: '/_authenticated/privacy-settings'
      path: '/privacy-settings'
      fullPath: '/privacy-settings'
      preLoaderRoute: typeof AuthenticatedPrivacySettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identity': {
      id: '/_authenticated/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof AuthenticatedIdentityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-listing': {
      id: '/_authenticated/create-listing'
      path: '/create-listing'
      fullPath: '/create-listing'
      preLoaderRoute: typeof AuthenticatedCreateListingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_super_admin': {
      id: '/_authenticated/_super_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSuper_adminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listings/': {
      id: '/_authenticated/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof AuthenticatedListingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/u/$slug': {
      id: '/_public/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof PublicUSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/tour/$slug': {
      id: '/_public/tour/$slug'
      path: '/tour/$slug'
      fullPath: '/tour/$slug'
      preLoaderRoute: typeof PublicTourSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/listings/$id': {
      id: '/_authenticated/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof AuthenticatedListingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_super_admin/sponsorship/': {
      id: '/_authenticated/_super_admin/sponsorship/'
      path: '/sponsorship'
      fullPath: '/sponsorship/'
      preLoaderRoute: typeof AuthenticatedSuper_adminSponsorshipIndexRouteImport
      parentRoute: typeof AuthenticatedSuper_adminRouteRoute
    }
    '/_authenticated/listings/$id/report': {
      id: '/_authenticated/listings/$id/report'
      path: '/report'
      fullPath: '/listings/$id/report'
      preLoaderRoute: typeof AuthenticatedListingsIdReportRouteImport
      parentRoute: typeof AuthenticatedListingsIdRoute
    }
    '/_authenticated/listings/$id/analytics': {
      id: '/_authenticated/listings/$id/analytics'
      path: '/analytics'
      fullPath: '/listings/$id/analytics'
      preLoaderRoute: typeof AuthenticatedListingsIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedListingsIdRoute
    }
    '/_authenticated/_super_admin/sponsorship/new': {
      id: '/_authenticated/_super_admin/sponsorship/new'
      path: '/sponsorship/new'
      fullPath: '/sponsorship/new'
      preLoaderRoute: typeof AuthenticatedSuper_adminSponsorshipNewRouteImport
      parentRoute: typeof AuthenticatedSuper_adminRouteRoute
    }
    '/_authenticated/_super_admin/sponsorship/$campaignId': {
      id: '/_authenticated/_super_admin/sponsorship/$campaignId'
      path: '/sponsorship/$campaignId'
      fullPath: '/sponsorship/$campaignId'
      preLoaderRoute: typeof AuthenticatedSuper_adminSponsorshipCampaignIdRouteImport
      parentRoute: typeof AuthenticatedSuper_adminRouteRoute
    }
  }
}

interface AuthenticatedSuper_adminRouteRouteChildren {
  AuthenticatedSuper_adminSponsorshipCampaignIdRoute: typeof AuthenticatedSuper_adminSponsorshipCampaignIdRoute
  AuthenticatedSuper_adminSponsorshipNewRoute: typeof AuthenticatedSuper_adminSponsorshipNewRoute
  AuthenticatedSuper_adminSponsorshipIndexRoute: typeof AuthenticatedSuper_adminSponsorshipIndexRoute
}

const AuthenticatedSuper_adminRouteRouteChildren: AuthenticatedSuper_adminRouteRouteChildren =
  {
    AuthenticatedSuper_adminSponsorshipCampaignIdRoute:
      AuthenticatedSuper_adminSponsorshipCampaignIdRoute,
    AuthenticatedSuper_adminSponsorshipNewRoute:
      AuthenticatedSuper_adminSponsorshipNewRoute,
    AuthenticatedSuper_adminSponsorshipIndexRoute:
      AuthenticatedSuper_adminSponsorshipIndexRoute,
  }

const AuthenticatedSuper_adminRouteRouteWithChildren =
  AuthenticatedSuper_adminRouteRoute._addFileChildren(
    AuthenticatedSuper_adminRouteRouteChildren,
  )

interface AuthenticatedListingsIdRouteChildren {
  AuthenticatedListingsIdAnalyticsRoute: typeof AuthenticatedListingsIdAnalyticsRoute
  AuthenticatedListingsIdReportRoute: typeof AuthenticatedListingsIdReportRoute
}

const AuthenticatedListingsIdRouteChildren: AuthenticatedListingsIdRouteChildren =
  {
    AuthenticatedListingsIdAnalyticsRoute:
      AuthenticatedListingsIdAnalyticsRoute,
    AuthenticatedListingsIdReportRoute: AuthenticatedListingsIdReportRoute,
  }

const AuthenticatedListingsIdRouteWithChildren =
  AuthenticatedListingsIdRoute._addFileChildren(
    AuthenticatedListingsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSuper_adminRouteRoute: typeof AuthenticatedSuper_adminRouteRouteWithChildren
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRoute
  AuthenticatedCreateListingRoute: typeof AuthenticatedCreateListingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRoute
  AuthenticatedIdentityRoute: typeof AuthenticatedIdentityRoute
  AuthenticatedPrivacySettingsRoute: typeof AuthenticatedPrivacySettingsRoute
  AuthenticatedResolvedVisitorsRoute: typeof AuthenticatedResolvedVisitorsRoute
  AuthenticatedTestCenterRoute: typeof AuthenticatedTestCenterRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRoute
  AuthenticatedTrackingVerifyRoute: typeof AuthenticatedTrackingVerifyRoute
  AuthenticatedListingsIdRoute: typeof AuthenticatedListingsIdRouteWithChildren
  AuthenticatedListingsIndexRoute: typeof AuthenticatedListingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSuper_adminRouteRoute:
    AuthenticatedSuper_adminRouteRouteWithChildren,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRoute,
  AuthenticatedCreateListingRoute: AuthenticatedCreateListingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemoRoute: AuthenticatedDemoRoute,
  AuthenticatedIdentityRoute: AuthenticatedIdentityRoute,
  AuthenticatedPrivacySettingsRoute: AuthenticatedPrivacySettingsRoute,
  AuthenticatedResolvedVisitorsRoute: AuthenticatedResolvedVisitorsRoute,
  AuthenticatedTestCenterRoute: AuthenticatedTestCenterRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRoute,
  AuthenticatedTrackingVerifyRoute: AuthenticatedTrackingVerifyRoute,
  AuthenticatedListingsIdRoute: AuthenticatedListingsIdRouteWithChildren,
  AuthenticatedListingsIndexRoute: AuthenticatedListingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicCookiesRoute: typeof PublicCookiesRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicPrivacyChoicesRoute: typeof PublicPrivacyChoicesRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicTourSlugRoute: typeof PublicTourSlugRoute
  PublicUSlugRoute: typeof PublicUSlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicCookiesRoute: PublicCookiesRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicPrivacyChoicesRoute: PublicPrivacyChoicesRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicTourSlugRoute: PublicTourSlugRoute,
  PublicUSlugRoute: PublicUSlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
